android.enableJetifier=true
android.useAndroidX=true
kapt.use.worker.api=false
buildNumber=
artifactory_username=
artifactory_password=
org.gradle.jvmargs=-Xmx4096M
android.disableAutomaticComponentCreation=true

GROUP=com.gap.androidlibraries
POM_ARTIFACT_ID=hoodies-networkandroid
VERSION_NAME=1.0.2-SNAPSHOT

POM_NAME=Hoodies-Network
POM_DESCRIPTION=A modern, type-safe, and high-performance Android HTTP library made by Gap Inc. 
POM_INCEPTION_YEAR=2023
POM_URL=https://github.com/gapinc/hoodies-network

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://github.com/gapinc/hoodies-network/blob/main/LICENSE.md
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/gapinc/hoodies-network
POM_SCM_CONNECTION=scm:git:git://github.com/gapinc/hoodies-network.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/gapinc/hoodies-network.git

POM_DEVELOPER_ID=gapinc
POM_DEVELOPER_NAME=Gap Inc.
POM_DEVELOPER_URL=https://github.com/gapinc