= Hoodies-Network
:toc:
:source-highlighter: highlightjs

== Introduction
Hoodies-Network is a modern, type-safe and high-performance Android HTTP library.
It was originally designed for use in Gap's Instant Apps. It:

* Offers a highly competitive feature set while being smaller than other libraries
* Is Kotlin-native
* Is designed using a philosophy of simple and clean design/architecture

Though its feature set has expanded over time to match and sometimes exceed other libraries, its Instant App roots remain and the post-minification apk size is still the smallest.

== Features
* URL parameter replacement and query parameter support
* Object conversion to request body (e.g., JSON, protocol buffers)
* Object conversion from response body (e.g., JSON, protocol buffers, images)
* Custom header support
* Multiple and multipart file upload
* Support for POST, GET, PATCH, PUT, and DELETE methods
* Success and failure callbacks
* Request, error, network, response, request body encryption, and response body decryption interceptors
* Automatic retry on failure
* Use of SSLSocketFactory
* Advanced mock web server
* Advanced optionally encrypted cache system
* Built-in cookie handling including encrypted persistent local storage

== Usage Guide
=== Getting Started
. Integrate this library as a dependency in your project:
.. Clone this project and publish it to your local Maven repository:
... (In Android Studio top menu) Build -> Clean Build
... Build -> Make Module 'Hoodies-Network.Hoodies-Network'
... Gradle -> Tasks -> publishing -> publishAarPublicationToMavenLocal
.. Use Gradle to add it as a dependency in your project: 
... `implementation "com.gap.androidlibraries:hoodies-networkandroid:latest"`
. Build your HttpClient:

[source,kotlin]
----
val defaultHeaders = hashMapOf(
        CONTENT_TYPE_KEY to APPLICATION_JSON, MULTIDB_ENABLED to MULTIDB_ENABLED_VALUE,
        CLIENT_ID to CLIENT_ID_VALUE,
        CLIENT_OS to CLIENT_OS_VALUE
    )

val client = HoodiesNetworkClient.Builder()
    .baseUrl(baseUrl)
    .addHeaders(defaultHeaders)
    //More on Interceptors later
    .addInterceptor(sessionInterceptor)
    //More on automatic retry later
    .retryOnConnectionFailure(true, HoodiesNetworkClient.RetryCount.RETRY_MAX)
    .build()
----

=== Using Interceptors
Optionally, you can create an Interceptor Class which inherits from com.gap.network.interceptor.Interceptor Interceptors allow you read/modify all properties (headers, body, etc) of requests and responses before they are executed/delivered.

`CancellableMutableRequests` can be cancelled by calling `cancellableMutableRequest.cancelRequest(Success(object to return))` or `cancellableMutableRequest.cancelRequest(Failure(message, code, throwable))` - depending on what you want to return.

`RetryableCancellableMutableRequests` can be cancelled as well as retried. If the request has its body or headers changed, the retry attempt will execute the request with those changes intact.

[source,kotlin]
----
class SessionInterceptor(context: Context) : Interceptor(context) {

    override fun interceptRequest(identifier: String, cancellableMutableRequest: CancellableMutableRequest) {
        //Called after interceptNetwork, just before a request is executed
    }

    override fun interceptError(error: GapError, retryableCancellableMutableRequest: RetryableCancellableMutableRequest, autoRetryAttempts: Int) {
        //This is invoked before the failure callback is called, so you can retry the request if, for example, it fails because of expired authorization data:
	//if (error.code == 403) {
	//	val headers = retryableCancellableMutableRequest.request.getHeaders().toMutableMap()        	
	//	headers["Authorization"] = getNewAuthorization()
        //	retryableCancellableMutableRequest.request.setRequestHeaders(headers)
	//
	//  	retryableCancellableMutableRequest.retryRequest()
	//}
    }

    override fun interceptNetwork(isOnline: Boolean, cancellableMutableRequest: CancellableMutableRequest) {
	//This is the first interceptor that is invoked. Here, you can define what happens if the device knows that it is offline
        //If you don't want the request to be executed if there is no network connection, you can do something like this:
	//if (!isOnline) { cancellableMutableRequest.cancelRequest(Failure(GapError("No connection!", 0, SocketTimeoutException("No connection!")))) }
    }

    override fun interceptResponse(result: Result<*, GapError>, request: Request<Any>?) {
        //This is invoked upon the successful completion of a request before the success object is returned
    }
}
----

=== Using Automatic Retry
If a request fails due to a `SocketTimeoutException` or `IOException`, Hoodies-Network can automatically retry the request a specific amount of times. 

Retry is configured in the `HoodiesNetworkClient.Builder()` with the `.retryOnConnectionFailure(true, HoodiesNetworkClient.RetryCount.RETRY_MAX)` method.

The following options are available:

* `HoodiesNetworkClient.RetryCount.RETRY_NEVER`
* `HoodiesNetworkClient.RetryCount.RETRY_ONCE`
* `HoodiesNetworkClient.RetryCount.RETRY_TWICE`
* `HoodiesNetworkClient.RetryCount.RETRY_THRICE`
* `HoodiesNetworkClient.RetryCount.RETRY_MAX`

=== Configuring Timeouts
* Connect timeout can be configured using `HttpClientConfig.setConnectTimeOut(Duration.ofSeconds(seconds))`
* Read timeout can be configured using `HttpClientConfig.setReadTimeOut(Duration.ofSeconds(seconds))`
* Setting the duration to 0 will make the timeout infinite
* Changes apply to all `HttpClients`
* Defaults can be restored using `HttpClientConfig.setFactoryDefaultConfiguration()`

=== Handling Cookies
By default, all cookies are ignored. Cookie retention and manipulation can be performed as follows:

. Pass a `CookieJar` to the `.enableCookiesWithCookieJar()` method of the `HoodiesNetworkClient.Builder()`:
.. (For most use-cases) Use the `CookieJar()`
.. (If cookies must persist across app launches) Use the `PersistentCookieJar("myPersistentCookieJar", context)` - Cookies are securely encrypted while in storage
. Manipulate the contents of the `CookieJar` using the following methods:
.. `getCookiesForHost(host: URI) : List<HttpCookie>` gets all the cookies for a specified host
.. `getAllCookies() : List<HttpCookie>` gets all the cookies stored in the `CookieJar`
.. `getAllHosts() : List<URI>` gets a list of all hosts that have stored cookies in the `CookieJar`
.. `setCookiesForHost(host: URI, cookies: List<HttpCookie>)` overwrites all the cookies for the specified host with those in the passed list 
.. `addCookieForHost(host: URI, cookie: HttpCookie)` adds the passed cookie for the specified host 
.. `removeAllCookies()` deleted all cookies in the `CookieJar`

=== Using the Cache
By default, no data is cached. Caching can be configured and enabled as follows:

. Create a `CacheEnabled` object 
.. If the data in the cache needs to be encrypted, set `encryptionEnabled = true`
.. Decide what the stale data threshold should be and set it: `staleDataThreshold = Duration.ofSeconds(60)`
.. Instantiate the object: `val cacheConfiguration = CacheEnabled(encryptionEnabled = true, staleDataThreshold = Duration.ofSeconds(60), context)`
. Pass the `CacheEnabled`` object to the `cacheConfiguration`` parameter when making a network request:

[source,kotlin]
----
return@withContext client.getUrlQueryParam<LocationAttribute>(
        queryParams = queryParams,
        api = pathParams,
        cacheConfiguration = cacheConfiguration
    )
----

=== Using Encryption/Decryption Interceptors
Encryption/decryption of the request and response bodies can be implemented by passing an `EncryptionDecryptionInterceptor` to the `.addEncryptionDecryptionInterceptor(encDecInterceptor)` method of the `HoodiesNetworkClient.Builder()`.

[source,kotlin]
----
val encDecInterceptor = EncDecInterceptor(this.context)

class EncDecInterceptor(override val context: Context) : EncryptionDecryptionInterceptor {

    override fun decryptResponse(response: ByteArray): ByteArray {
        // add your decryption logic here
        return  ByteArray(1)
    }

    override fun encryptAdditionalHeaders(additionalHeaderValue: ByteArray): ByteArray {
        // add your encryption logic here
        return  ByteArray(1)
    }

    override fun encryptRequest(requestBodyOrUrlQueryParamKeyValue: ByteArray): ByteArray {
        // add your encryption logic here
        return  ByteArray(1)
    }
}
----

=== Using the MockWebServer
The MockWebServer can replicate your API endpoints for unit testing purposes.

1. Create a `MockWebServerManager.Builder()` and set the port: `val serverBuilder = MockWebServerManager.Builder().usePort(5000)`
2. Mock your API endpoints:

    a. (For simple use-cases) Using the MockServerMaker DSL:

[source,kotlin]
----
//Make request body
val body = JSONObject()
body.put("name", "test_1")
body.put("salary", "1234")
body.put("age", "123")

//Make request headers
val reqHeaders: MutableMap<String, String> = HashMap()
reqHeaders["key"] = "value"

//Mock response
val response = "{\"status\":\"success\",\"data\":{\"name\":\"test_1\",\"salary\":\"1234\",\"age\":\"123\",\"id\":9221},\"message\":\"Successfully! Record has been added.\"}"

//Set up MockWebServer builder with port
val serverBuilder = MockWebServerManager.Builder().usePort(5000)

//Set up handler on MockWebServer to accept the request body and headers from above
MockServerMaker.Builder()
    .acceptMethod(HoodiesNetworkClient.HttpMethod.POST)
    .expect(body) //Can also be a HashMap<String, String> to validate URL-encoded params
    .expectHeaders(reqHeaders)
    .returnThisJsonIfInputMatches(JSONObject(response))
    .applyToMockWebServerBuilder("/test", serverBuilder)
---- 
[start=2]
2. Mock your API endpoints (continued):
[start=2]
    b. (For advanced behavior) By making a WebServerHandler() for your endpoint:

[source,kotlin]
----
val handler = object : WebServerHandler() {
    override fun handleRequest(call: HttpCall) {
        when (method) {
            //KTor-like syntax
            get {
                val delayLength = call.httpExchange.requestURI.toString().split("/").last()
                Thread.sleep(delayLength.toLong() * 1000L)
                call.respond(200, "{\"delay\":\"$delayLength\"}")
            }
            post {
                val delayLength = call.httpExchange.requestURI.toString().split("/").last()
                Thread.sleep(delayLength.toLong() * 1000L)
                call.respond(200, "{\"delay\":\"$delayLength\"}")
            }
        }
    }
}

serverBuilder.addContext("/echodelay", handler)
---- 

[start=3]
3. Start the MockWebServer: `val server = serverBuilder.start()`
4. Run your tests
5. Stop the MockWebServer: `server.stop()`

=== More usage examples
There are many more usage examples in the https://github.com/gapinc/hoodies-network/tree/main/examples[examples folder].

== Running Tests
The test classes package path is at com.gap.hoodies_network(androidTest). The test classes use test libraries Mockito and Junit, and run on an Android device. The MockWebServer is used to host the endpoints for the tests. The test classes are as follows:

* CachingAndCryptographyTest
* FormUrlEncodedRequestTest
* EncryptionDecryptionTest
* FileUploadRequestTests
* HoodiesNetworkClientTest
* HeaderTest
* ImageRequestMockTest
* ImageTests
* JsonRequestTest
* MultiRequestTest
* NetworkConnectionTest
* ResponseDeliveryInstant
* ResponseTest
* RetryTest
* SocketTimeOutTest
* StringRequestTest
* UrlResolverTest
* CookieTests

You can run the tests by right-clicking on the androidTest folder and then clicking "Run Tests".

Note: Having your Android emulator or physical device connected is required.

== Environment Setup
* This is a Gradle project. You can use any Android and Gradle-compatible IDE. Use of Android Studio is highly suggested.

* Android Studio Bumblebee and above are supported.

* It it also highly recommended that you have an emulator or physical device connected - this allows you to run the unit tests.

== Conduct
This is a professional environment and you are expected to conduct yourself in a professional and courteous manner. If you fail to exhibit appropriate conduct, your contributions and interactions will no longer be welcome here.

== Contributing
* All are welcome and encouraged to contribute. If you are looking for a place to start, try working on an unassigned issue with the `#good-first-issue` tag. 

* All contributions are expected to conform to standard Kotlin code style and be covered by unit tests.

* If you open a pull request with failing tests, your PR will not be merged and you will be asked to resolve the issue. 

* If you would like to contribute code you can do so through GitHub by forking the repository and sending a pull request. 

* When submitting code, please make every effort to follow existing conventions and style in order to keep the code as readable as possible. 

* Please also make sure your code compiles and passes all tests by running `./gradlew clean build` (or gradlew.bat clean build for Windows).
