name: Release Build and Publish

on:
  push:
    branches: [ release/** ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant Permission for gradlew to execute
        run: chmod +x gradlew

      - name: Build AAR
        run: ./gradlew assembleRelease

      - name: Publish to GitHub Package Registry
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Hoodies-Network AAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Hoodies-Network/build/outputs/aar/Hoodies-Network-release.aar
          asset_name: Hoodies-Network-release.aar
          asset_content_type: application/aar

