name: Release Build and Publish

on:
  push:
    branches: [ release/** ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant Permission for gradlew to execute
        run: chmod +x gradlew

      - name: Build AAR
        run: ./gradlew assembleRelease

      - name: Publish to GitHub Package Registry
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

